# Generated by Django 5.1 on 2024-08-19 07:45

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='descrption',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publicationcomment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='journal.publication'),
        ),
    ]
