# Generated by Django 5.1 on 2024-08-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_post_alter_aboutme_descrption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Хэштег',
                'verbose_name_plural': 'Хэштеги',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='publication',
            name='hashteg',
            field=models.ManyToManyField(to='journal.hashtag'),
        ),
    ]
